//! Cross-repo contract, proven with real bytes: the fixture is an actual
//! unified-config body generated by LogPacer's `Agent#unified_config_directive`
//! (selector-backed service on a seeded account; endpoints sanitized). If this
//! test fails after a LogPacer change, regenerate the fixture from a seeded
//! account rather than hand-editing it — its value is being real output.

use std::collections::HashMap;

use edgepacer::config::{
    UnifiedConfig, all_service_descriptions, resolved_collect_from_config, selector_matches,
};
use edgepacer::discovery::cache::DiscoveryCache;
use edgepacer::discovery::{Census, Container};

const GOLDEN: &str = include_str!("fixtures/unified_config_golden.json");

fn golden_config() -> UnifiedConfig {
    let raw: serde_json::Value = serde_json::from_str(GOLDEN).expect("golden body is valid JSON");
    UnifiedConfig::new(raw, "golden-etag".to_string())
}

fn kamal_container(role: &str, destination: &str) -> Container {
    let mut labels = HashMap::new();
    labels.insert("service".to_string(), "golden".to_string());
    labels.insert("role".to_string(), role.to_string());
    labels.insert("destination".to_string(), destination.to_string());

    Container {
        id: "abc123def456".into(),
        name: format!("golden-{role}-{destination}-1a2b3c4"),
        service_name: "golden-web".into(),
        service_name_explicit: false,
        image: "ghcr.io/golden/web:abc".into(),
        state: "running".into(),
        labels,
        env: vec![],
        runtime: "docker".into(),
        log_path: String::new(),
        log_format: "plain_text".into(),
        pod_uid: String::new(),
        pod_name: String::new(),
        namespace: String::new(),
        node_name: String::new(),
        deployment: String::new(),
        workload_kind: String::new(),
        container_id: "abc123def456".into(),
        container_name: String::new(),
    }
}

fn cache_with(containers: Vec<Container>) -> DiscoveryCache {
    let mut cache = DiscoveryCache::new();
    cache.update_all(&Census {
        containers,
        ..Default::default()
    });
    cache
}

#[test]
fn golden_body_parses_exactly_the_shipped_service_description() {
    let descriptions = all_service_descriptions(&golden_config());

    assert_eq!(descriptions.len(), 1);
    let description = &descriptions[0];
    assert_eq!(description.service_slug, "golden-web");
    assert_eq!(description.collect.log_source_id, "service-3");

    let selector: Vec<(&str, &str)> = description
        .selector
        .iter()
        .map(|(k, v)| (k.as_str(), v.as_str()))
        .collect();
    assert_eq!(
        selector,
        vec![
            ("kamal.destination", "prod"),
            ("kamal.role", "web"),
            ("kamal.service", "golden"),
        ]
    );
}

#[test]
fn golden_selector_matches_the_kamal_container_atoms() {
    let descriptions = all_service_descriptions(&golden_config());
    let container = kamal_container("web", "prod");

    assert!(selector_matches(
        &descriptions[0].selector,
        &container.identifier_set()
    ));
    assert!(!selector_matches(
        &descriptions[0].selector,
        &kamal_container("web", "staging").identifier_set()
    ));
}

#[test]
fn golden_body_resolves_one_pipeline_with_claim_dedup_and_adoption() {
    let config = golden_config();
    let cache = cache_with(vec![kamal_container("web", "prod")]);

    let resolved = resolved_collect_from_config(&config, &cache);

    // The description claims the container: exactly one source, with the
    // synthesized id extending the legacy one.
    let streaming_ids: Vec<&str> = resolved
        .streaming_sources
        .iter()
        .map(|s| s.log_source_id.as_str())
        .collect();
    assert_eq!(streaming_ids, vec!["service-3/golden-web-prod"]);
    assert!(resolved.file_streams.is_empty());

    // Dual emission on the wire, one pipeline on the agent: the legacy
    // env_var stream (same container via its service-name alias) is claimed.
    assert!(!streaming_ids.contains(&"service-3"));

    // The env-var→selector swap adopts the legacy checkpoint state dir.
    assert_eq!(resolved.checkpoint_adoptions.len(), 1);
    assert_eq!(
        resolved.checkpoint_adoptions[0].legacy_log_source_id,
        "service-3"
    );
    assert_eq!(
        resolved.checkpoint_adoptions[0].log_source_id,
        "service-3/golden-web-prod"
    );
}

#[test]
fn golden_body_without_matching_containers_resolves_nothing_for_the_service() {
    let config = golden_config();
    // Same workload, wrong destination — the selector must not claim it, and
    // the legacy env_var stream must not resolve it either (different alias).
    let mut container = kamal_container("web", "staging");
    container.service_name = "other".into();
    let cache = cache_with(vec![container]);

    let resolved = resolved_collect_from_config(&config, &cache);

    assert!(
        resolved
            .streaming_sources
            .iter()
            .all(|s| !s.log_source_id.starts_with("service-3"))
    );
}
