{{- if .Values.auth.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "edgepacer.fullname" . }}
  labels:
    {{- include "edgepacer.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.auth.accountTokenKey }}: {{ required "auth.accountToken is required when auth.createSecret=true" .Values.auth.accountToken | quote }}
{{- end }}
